# Generated by Django 3.2.21 on 2023-09-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20230929_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Единицы оборудования'},
        ),
        migrations.AlterField(
            model_name='unit',
            name='vendor',
            field=models.CharField(choices=[('ABB', 'ABB'), ('Danfoss', 'Danfoss'), ('VACON', 'VACON'), ('ONI', 'ONI'), ('Schneider', 'Schneider')], default='ABB', max_length=250, verbose_name='Вендор'),
        ),
    ]
